### ISSUE TITLE
No module named 'sphinx_bootstrap_theme'

### ISSUE THREAD

**Issue by chethana-designer** [ryan-roemer/sphinx-bootstrap-theme#195]
I installed sphinx_boostrap_theme using below command -
pip install sphinx_bootstrap_theme

Then I imported the theme as below -
import sphinx_bootstrap_theme

Finally, I configured the HTML theme values in “conf.py”, as below -
html_theme = 'bootstrap'
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()

But I am getting the below error :(  Please please help me :(

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/Users/chethanakumar/Projects/PEM/docs/en_US/conf.py", line 18, in <module>
    import sphinx_bootstrap_theme
ModuleNotFoundError: No module named 'sphinx_bootstrap_theme'

make[1]: *** [html] Error 2
make: *** [docs] Error 2

Thanks,
Chethan

**Comment by ryan-roemer** [comment]
What is the output of `pip freeze` for the project?

**Comment by chethana-designer** [comment]
Hi Ryan,

When I tried to install on system python, it did not work. pip freeze show the package installed.
But when I created a venv and installed, it worked totally fine.
Its working for me now, so please don't bother. 

Thank you :)
